# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  # Configure provisioning
  config.vm.provision "shell", path: "bootstrap.sh"
  # Configure network ports
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 1024
      vb.gui = false
      vb.name = "kafka"
  end
end
